CREATE DATABASE MiriamGaGuMuk;

# Schema

CREATE TABLE Artist (
    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL
);

CREATE TABLE Album (
    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Num_Tracks INT NOT NULL,
    ArtistId INT,
    FOREIGN KEY (ArtistId) REFERENCES Artist(Id)

);

CREATE TABLE Track (
    Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Duration TIME('00:00:00'),
    AlbumId INT,
    FOREIGN KEY (AlbumId) REFERENCES Album(Id)
);